// Women
import womenImgOne from "./assets/img/shop/women/shop-1.png";
import womenImgTwo from "./assets/img/shop/women/shop-2.png";
import womenImgThree from "./assets/img/shop/women/shop-3.png";
import womenImgFour from "./assets/img/shop/women/shop-4.png";
import womenImgFive from "./assets/img/shop/women/shop-5.png";
import womenImgSix from "./assets/img/shop/women/shop-6.png";
import womenImgSeven from "./assets/img/shop/women/shop-7.png";
import womenImgEight from "./assets/img/shop/women/shop-8.png";
import womenImgNine from "./assets/img/shop/women/shop-9.png";
//   Men
import menImgOne from "./assets/img/shop/men/shop-1.png";
import menImgTwo from "./assets/img/shop/men/shop-2.png";
import menImgThree from "./assets/img/shop/men/shop-3.png";
import menImgFour from "./assets/img/shop/men/shop-4.png";
import menImgFive from "./assets/img/shop/men/shop-5.png";
import menImgSix from "./assets/img/shop/men/shop-6.png";
import menImgSeven from "./assets/img/shop/men/shop-7.png";
import menImgEight from "./assets/img/shop/men/shop-8.png";
import menImgNine from "./assets/img/shop/men/shop-9.png";
// Unisex
import unisexImgOne from "./assets/img/shop/unisex/shop-1.png";
import unisexImgTwo from "./assets/img/shop/unisex/shop-2.png";
import unisexImgThree from "./assets/img/shop/unisex/shop-3.png";
import unisexImgFour from "./assets/img/shop/unisex/shop-4.png";
import unisexImgFive from "./assets/img/shop/unisex/shop-5.png";
import unisexImgSix from "./assets/img/shop/unisex/shop-6.png";
import unisexImgSeven from "./assets/img/shop/unisex/shop-7.png";
import unisexImgEight from "./assets/img/shop/unisex/shop-8.png";
import unisexImgNine from "./assets/img/shop/unisex/shop-9.png";
// Kids
import kidsImgOne from "./assets/img/shop/kids/shop-1.png";
import kidsImgTwo from "./assets/img/shop/kids/shop-2.png";
import kidsImgThree from "./assets/img/shop/kids/shop-3.png";
import kidsImgFour from "./assets/img/shop/kids/shop-4.png";
import kidsImgFive from "./assets/img/shop/kids/shop-5.png";
import kidsImgSix from "./assets/img/shop/kids/shop-6.png";
import kidsImgSeven from "./assets/img/shop/kids/shop-7.png";
import kidsImgEight from "./assets/img/shop/kids/shop-8.png";
import kidsImgNine from "./assets/img/shop/kids/shop-9.png";
// Sports Wear
import sportsImgOne from "./assets/img/shop/sports/shop-1.png";
import sportsImgTwo from "./assets/img/shop/sports/shop-2.png";
import sportsImgThree from "./assets/img/shop/sports/shop-3.png";
import sportsImgFour from "./assets/img/shop/sports/shop-4.png";
import sportsImgFive from "./assets/img/shop/sports/shop-5.png";
import sportsImgSix from "./assets/img/shop/sports/shop-6.png";
import sportsImgSeven from "./assets/img/shop/sports/shop-7.png";
import sportsImgEight from "./assets/img/shop/sports/shop-8.png";
import sportsImgNine from "./assets/img/shop/sports/shop-9.png";
export const products = [
  // Women
  {
    catName: "Nike Women’s Tracksuit",
    brand: "Nike",
    price: "95.50",
    rate: 5,
    soldOut: false,
    img: womenImgOne,
    category: "Women's Fashion",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "980.00",
    rate: 4,
    soldOut: false,
    img: womenImgTwo,
    category: "Women's Fashion",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "300.50",
    rate: 4,
    soldOut: false,
    img: womenImgThree,
    category: "Women's Fashion",
  },
  {
    catName: "Roller Rabbit",
    brand: "Gucci",
    price: "30.500",
    rate: 5,
    soldOut: false,
    img: womenImgFour,
    category: "Women's Fashion",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "200.00",
    rate: 5,
    soldOut: false,
    img: womenImgFive,
    category: "Women's Fashion",
  },
  {
    catName: "Roller Rabbit",
    brand: "Nike",
    price: "100.00",
    rate: 4,
    soldOut: true,
    img: womenImgSix,
    category: "Women's Fashion",
  },
  {
    catName: "Nike Women’s Tracksuit",
    brand: "Nike",
    price: "95.50",
    rate: 5,
    soldOut: false,
    img: womenImgSeven,
    category: "Women's Fashion",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "980.00",
    rate: 4,
    soldOut: false,
    img: womenImgEight,
    category: "Women's Fashion",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "300.50",
    rate: 4,
    soldOut: false,
    img: womenImgNine,
    category: "Women's Fashion",
  },
  {
    catName: "Nike Women’s Tracksuit",
    brand: "Nike",
    price: "95.50",
    rate: 5,
    soldOut: false,
    img: womenImgOne,
    category: "Women's Fashion",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "980.00",
    rate: 4,
    soldOut: false,
    img: womenImgTwo,
    category: "Women's Fashion",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "300.50",
    rate: 4,
    soldOut: false,
    img: womenImgThree,
    category: "Women's Fashion",
  },
  {
    catName: "Roller Rabbit",
    brand: "Gucci",
    price: "30.500",
    rate: 5,
    soldOut: false,
    img: womenImgFour,
    category: "Women's Fashion",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "200.00",
    rate: 5,
    soldOut: false,
    img: womenImgFive,
    category: "Women's Fashion",
  },
  {
    catName: "Roller Rabbit",
    brand: "Nike",
    price: "100.00",
    rate: 4,
    soldOut: true,
    img: womenImgSix,
    category: "Women's Fashion",
  },
  {
    catName: "Nike Women’s Tracksuit",
    brand: "Nike",
    price: "95.50",
    rate: 5,
    soldOut: false,
    img: womenImgSeven,
    category: "Women's Fashion",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "980.00",
    rate: 4,
    soldOut: false,
    img: womenImgEight,
    category: "Women's Fashion",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "300.50",
    rate: 4,
    soldOut: false,
    img: womenImgNine,
    category: "Women's Fashion",
  },
  //   Men
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "300.50",
    rate: 4,
    soldOut: false,
    img: menImgOne,
    category: "Men's Fashion",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "300.50",
    rate: 4,
    soldOut: false,
    img: menImgTwo,
    category: "Men's Fashion",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "300.50",
    rate: 4,
    soldOut: false,
    img: menImgThree,
    category: "Men's Fashion",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "300.50",
    rate: 4,
    soldOut: false,
    img: menImgFour,
    category: "Men's Fashion",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "300.50",
    rate: 4,
    soldOut: false,
    img: menImgFive,
    category: "Men's Fashion",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "300.50",
    rate: 4,
    soldOut: false,
    img: menImgSix,
    category: "Men's Fashion",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "300.50",
    rate: 4,
    soldOut: false,
    img: menImgSeven,
    category: "Men's Fashion",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "300.50",
    rate: 4,
    soldOut: false,
    img: menImgEight,
    category: "Men's Fashion",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "300.50",
    rate: 4,
    soldOut: false,
    img: menImgNine,
    category: "Men's Fashion",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "300.50",
    rate: 4,
    soldOut: false,
    img: menImgOne,
    category: "Men's Fashion",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "300.50",
    rate: 4,
    soldOut: false,
    img: menImgTwo,
    category: "Men's Fashion",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "300.50",
    rate: 4,
    soldOut: false,
    img: menImgThree,
    category: "Men's Fashion",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "300.50",
    rate: 4,
    soldOut: false,
    img: menImgFour,
    category: "Men's Fashion",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "300.50",
    rate: 4,
    soldOut: false,
    img: menImgFive,
    category: "Men's Fashion",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "300.50",
    rate: 4,
    soldOut: false,
    img: menImgSix,
    category: "Men's Fashion",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "300.50",
    rate: 4,
    soldOut: false,
    img: menImgSeven,
    category: "Men's Fashion",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "300.50",
    rate: 4,
    soldOut: false,
    img: menImgEight,
    category: "Men's Fashion",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "300.50",
    rate: 4,
    soldOut: false,
    img: menImgNine,
    category: "Men's Fashion",
  },
  // Unisex
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "300.50",
    rate: 4,
    soldOut: false,
    img: unisexImgOne,
    category: "Unisex",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "300.50",
    rate: 4,
    soldOut: false,
    img: unisexImgTwo,
    category: "Unisex",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "300.50",
    rate: 4,
    soldOut: false,
    img: unisexImgThree,
    category: "Unisex",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "300.50",
    rate: 4,
    soldOut: false,
    img: unisexImgFour,
    category: "Unisex",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "300.50",
    rate: 4,
    soldOut: false,
    img: unisexImgFive,
    category: "Unisex",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "300.50",
    rate: 4,
    soldOut: false,
    img: unisexImgSix,
    category: "Unisex",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "300.50",
    rate: 4,
    soldOut: false,
    img: unisexImgSeven,
    category: "Unisex",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "300.50",
    rate: 4,
    soldOut: false,
    img: unisexImgEight,
    category: "Unisex",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "300.50",
    rate: 4,
    soldOut: false,
    img: unisexImgNine,
    category: "Unisex",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "300.50",
    rate: 4,
    soldOut: false,
    img: unisexImgOne,
    category: "Unisex",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "300.50",
    rate: 4,
    soldOut: false,
    img: unisexImgTwo,
    category: "Unisex",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "300.50",
    rate: 4,
    soldOut: false,
    img: unisexImgThree,
    category: "Unisex",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "300.50",
    rate: 4,
    soldOut: false,
    img: unisexImgFour,
    category: "Unisex",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "300.50",
    rate: 4,
    soldOut: false,
    img: unisexImgFive,
    category: "Unisex",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "300.50",
    rate: 4,
    soldOut: false,
    img: unisexImgSix,
    category: "Unisex",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "300.50",
    rate: 4,
    soldOut: false,
    img: unisexImgSeven,
    category: "Unisex",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "300.50",
    rate: 4,
    soldOut: false,
    img: unisexImgEight,
    category: "Unisex",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "300.50",
    rate: 4,
    soldOut: false,
    img: unisexImgNine,
    category: "Unisex",
  },
  // Kids
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "300.50",
    rate: 4,
    soldOut: false,
    img: kidsImgOne,
    category: "Kids",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "300.50",
    rate: 4,
    soldOut: false,
    img: kidsImgTwo,
    category: "Kids",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "300.50",
    rate: 4,
    soldOut: false,
    img: kidsImgThree,
    category: "Kids",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "300.50",
    rate: 4,
    soldOut: false,
    img: kidsImgFour,
    category: "Kids",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "300.50",
    rate: 4,
    soldOut: false,
    img: kidsImgFive,
    category: "Kids",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "300.50",
    rate: 4,
    soldOut: false,
    img: kidsImgSix,
    category: "Kids",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "300.50",
    rate: 4,
    soldOut: false,
    img: kidsImgSeven,
    category: "Kids",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "300.50",
    rate: 4,
    soldOut: false,
    img: kidsImgEight,
    category: "Kids",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "300.50",
    rate: 4,
    soldOut: false,
    img: kidsImgNine,
    category: "Kids",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "300.50",
    rate: 4,
    soldOut: false,
    img: kidsImgOne,
    category: "Kids",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "300.50",
    rate: 4,
    soldOut: false,
    img: kidsImgTwo,
    category: "Kids",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "300.50",
    rate: 4,
    soldOut: false,
    img: kidsImgThree,
    category: "Kids",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "300.50",
    rate: 4,
    soldOut: false,
    img: kidsImgFour,
    category: "Kids",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "300.50",
    rate: 4,
    soldOut: false,
    img: kidsImgFive,
    category: "Kids",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "300.50",
    rate: 4,
    soldOut: false,
    img: kidsImgSix,
    category: "Kids",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "300.50",
    rate: 4,
    soldOut: false,
    img: kidsImgSeven,
    category: "Kids",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "300.50",
    rate: 4,
    soldOut: false,
    img: kidsImgEight,
    category: "Kids",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "300.50",
    rate: 4,
    soldOut: false,
    img: kidsImgNine,
    category: "Kids",
  },
  // Sports Wear
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "300.50",
    rate: 4,
    soldOut: false,
    img: sportsImgOne,
    category: "Sports Wear",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "300.50",
    rate: 4,
    soldOut: false,
    img: sportsImgTwo,
    category: "Sports Wear",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "300.50",
    rate: 4,
    soldOut: false,
    img: sportsImgThree,
    category: "Sports Wear",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "300.50",
    rate: 4,
    soldOut: false,
    img: sportsImgFour,
    category: "Sports Wear",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "300.50",
    rate: 4,
    soldOut: false,
    img: sportsImgFive,
    category: "Sports Wear",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "300.50",
    rate: 4,
    soldOut: false,
    img: sportsImgSix,
    category: "Sports Wear",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "300.50",
    rate: 4,
    soldOut: false,
    img: sportsImgSeven,
    category: "Sports Wear",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "300.50",
    rate: 4,
    soldOut: false,
    img: sportsImgEight,
    category: "Sports Wear",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "300.50",
    rate: 4,
    soldOut: false,
    img: sportsImgNine,
    category: "Sports Wear",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "300.50",
    rate: 4,
    soldOut: false,
    img: sportsImgOne,
    category: "Sports Wear",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "300.50",
    rate: 4,
    soldOut: false,
    img: sportsImgTwo,
    category: "Sports Wear",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "300.50",
    rate: 4,
    soldOut: false,
    img: sportsImgThree,
    category: "Sports Wear",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "300.50",
    rate: 4,
    soldOut: false,
    img: sportsImgFour,
    category: "Sports Wear",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "300.50",
    rate: 4,
    soldOut: false,
    img: sportsImgFive,
    category: "Sports Wear",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "300.50",
    rate: 4,
    soldOut: false,
    img: sportsImgSix,
    category: "Sports Wear",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "300.50",
    rate: 4,
    soldOut: false,
    img: sportsImgSeven,
    category: "Sports Wear",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "300.50",
    rate: 4,
    soldOut: false,
    img: sportsImgEight,
    category: "Sports Wear",
  },
  {
    catName: "Roller Rabbit",
    brand: "Zara",
    price: "300.50",
    rate: 4,
    soldOut: false,
    img: sportsImgNine,
    category: "Sports Wear",
  },
];
